name: Runtimes Onmerge
on:
  push:
    branches:
      - master
jobs:
  build-golang-onmerge:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          cd ./stable/golang
          make build-all
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          images=( 
            'go:1.14'
            'go-init:1.14'
            'go-init:1.13'
          )
          for image in "${images[@]}"; do
            docker tag kubeless/${image} ciscom31/${image}
            docker push ciscom31/${image}
          done
  build-python-onmerge:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          cd ./stable/python
          make build-all
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          images=( 
            'python:3.6'
            'python:3.7'
            'python:3.8'
          )
          for image in "${images[@]}"; do
            docker tag kubeless/${image} ciscom31/${image}
            docker push ciscom31/${image}
          done
